[jlprofilecanvas]
git-tree-sha1 = "a910ea1b745c16784f3f8ce1f4b6f6d4da7d8da0"

    [[jlprofilecanvas.download]]
    sha256 = "3d26f40bcc1cb0a5168adf2f6747e80b574dbefa8aaa5c5a083553c3b00870bc"
    url = "https://github.com/pfitzseb/jl-profile.js/archive/refs/tags/v0.5.2.tar.gz"